#!/bin/bash

#Online Peers - A script using cjdcmd (https://github.com/inhies/cjdcmd) to check the connectivity of the peers listed in your cjdroute.conf
#Version: 1.3
#License: MIT
#Issues/ideas: http://gitboria.com/prurigro/cjdns-onlinepeers or prurigro@darkcloud.ca

#Define variables
CJDROUTE="/etc/cjdroute.conf"
TMPFILE="/tmp/cjdpeers.tmp"
JSAWK="/tmp/jsawk-${USER}.sh"
CJDCMD="cjdcmd"

function getjsawk {
  if [ $(command -v curl) ]; then
    curl -s -L http://github.com/micha/jsawk/raw/master/jsawk > "$JSAWK"
  elif [ $(command -v wget) ]; then
    wget -q -O "$JSAWK" http://github.com/micha/jsawk/raw/master/jsawk
  else
    echo "Neither curl nor wget are available in \$PATH, please install one to continue"
    exit
  fi
}

#Fail if .cjdnsadmin is not configured
if [ ! -f "$HOME"/.cjdnsadmin ]; then
  echo "You must configure your "$HOME"/.cjdnsadmin file with your admin credentials before running"
  exit 1
fi

#Fail if $CJDROUTE is empty or doesn't exist
if [ ! -f "$CJDROUTE" ]; then
  echo "Your cjdroute.conf is set to ${CJDROUTE}, but it doesn't exist at this location"
  exit 1
fi

#Download jsawk if it doesn't already exist of the file is empty
if [ ! -f "$JSAWK" ]; then
	getjsawk
elif [ $(cat "$JSAWK" | wc -m) = 0  ]; then 
	getjsawk
fi

#Zero the tempfile
echo -n > "$TMPFILE"

#Build list of connected peer ipv6 addresses the temp file
for ip in $($CJDCMD peers | grep -o -e "fc[^\ ]*"); do
	echo "$ip" >> "$TMPFILE"
done

#Grab each public key from the cjdroute.conf connectTo list, convert to ipv6 and see if it matches any listed in the temporary peer list created above
for pubkey in $(cat /etc/cjdroute.conf | /bin/bash "$JSAWK" -n 'out(this.interfaces.UDPInterface)' | \grep --color=never -o -E "[a-zA-Z0-9]*\.k"); do
	PUBIP=$($CJDCMD  ip "$pubkey" | \grep -o -E ^[^\ ]*)
	echo -n "${pubkey} - ${PUBIP}: "
	if [ $(\grep -c "$PUBIP" "$TMPFILE") = 0 ]; then
		echo "NOT CONNECTED"
	elif [ $(\grep -c "$PUBIP" "$TMPFILE") = 1 ]; then
		echo "CONNECTED"
	else
		echo "ERROR, PUBLIC KEY LISTED MORE THAN ONCE"
	fi
done

#Clean up temp file
rm "$TMPFILE"
